### ISSUE TITLE
CrewLink hard-crashes when running the itch.io build

### ISSUE THREAD

**Issue by heygleeson** [ottomated/CrewLink#14]
_(Running v2020.10.22.i)_

Was able to grab a screenshot of the corrupted data it tries to show before the app hard-crashes. Basically happens whenever CrewLink detects the game and tries to establish a connection.

Is it possible for CrewLink to support non-steam builds of Among Us?

![CrewLink_Q3NkLnz6j9](https://user-images.githubusercontent.com/1772788/99940006-7501fc80-2dbf-11eb-9ba7-a301a07cf108.png)

**Comment by ottomated** [comment]
It would require different offsets being found. I can't maintain that, unfortunately.

**Comment by nailuj29gaming** [comment]
I am also having this problem

**Comment by nailuj29gaming** [comment]
@ottomated what needs to be done to find the offset? I would be willing to do this, as most of my friends don't have the steam version

**Comment by ottomated** [comment]
Use Cheat Engine and edit a offset yml file in the server repository to match the itch offsets. Then this repo needs a PR to be able to detect whether the version is itch or steam.

**Comment by nailuj29gaming** [comment]
@ottomated Windows is not allowing me to install Cheat Engine. Is there any alternatives?

**Comment by doabi** [comment]
Sorry but I am not a big expert in this cheat engine program and i do nott really know how to do the mentioned tasks, can somebody help me?

**Comment by nailuj29gaming** [comment]
I could not even install the program with windows defender

**Comment by YOYITsM3M8** [comment]
> I could not even install the program with windows defender

So disable windows defender

**Comment by doabi** [comment]
I can install it but do not really know how to find offset with it

**Comment by YOYITsM3M8** [comment]
> I can install it but do not really know how to find offset with it

Same

**Comment by nailuj29gaming** [comment]
> 
> 
> > I can install it but do not really know how to find offset with it
> 
> Same

me too

**Comment by YOYITsM3M8** [comment]
> > 
> 
> > 
> 
> > > I can install it but do not really know how to find offset with it
> 
> > 
> 
> > Same
> 
> 
> 
> Me too. I also don't really want to disable Windows Defender, for obvious reasons.
> 
> 
> 
> 

- Disable it
- install
- turn it back on

**Comment by nailuj29gaming** [comment]
@YOYITsM3M8 Good idea. I'll try that later.

**Comment by aarushtools** [comment]
> > > I can install it but do not really know how to find offset with it
> > 
> > 
> > Same
> 
> Me too. I also don't really want to disable Windows Defender, for obvious reasons.

You can manually make an exception for cheat engine in Windows Defender and any other antiviruses you might have.
Make sure you install the right cheat engine, because there are some fakes that are only there to put viruses on your system.

**Comment by aarushtools** [comment]
> I can install it but do not really know how to find offset with it
@nailuj29gaming @YOYITsM3M8 @doabi 
You need to go to the **CrewLink-server** repo and then go to **/offsets/**
[Here's a direct link](https://github.com/ottomated/CrewLink-server/tree/master/offsets)
Then you can use cheat engine to look into your version of the game to find the required offsets.
###### Of course, it would just be simpler to get the Steam version of the game.

**Comment by nailuj29gaming** [comment]
@aarushtools Some people don't have steam, or game their steam key to a friend when they bought the itch version.

**Comment by Delicious-Pancackes** [comment]
I would be willing to help but I don't have the itch version of the game

**Comment by aarushtools** [comment]
> @aarushtools Some people don't have steam, or game their steam key to a friend when they bought the itch version. Also how do we find the offsets? I'm about 90% sure that's what @YOYITsM3M8 and @doabi were confused about

I’m not very familiar with Cheat Engine, however I have found a guide that may help you:
[Offset Guide](https://github.com/shlifedev/AmongUsMemory/blob/master/OffsetGuide.md)
###### also ignore the fact that this came from an among us hacking utility.

**Comment by doabi** [comment]
I have been looking to it how to solve this but I think it is way beyond my current knowledge :(

**Comment by nailuj29gaming** [comment]
@doabi I would be happy to do this when I have time (school has been taking most of it)

**Comment by doabi** [comment]
> @doabi I would be happy to do this when I have time (school has been taking most of it)

Okay than I will still follow this discussion in case you had time. :)

**Comment by YOYITsM3M8** [comment]
Ahhhh is getting so many pings

**Comment by nailuj29gaming** [comment]
I replied to one very active issue in a different repo and now I've been getting pings all day. I should change notification settings

**Comment by YOYITsM3M8** [comment]
> I replied to one very active issue in a different repo and now I've been getting pings all day. I should change notification settings

Yeah that happens to me a lot

**Comment by termitavee** [comment]
If I would like to help on this, what values do I have to search with cheat engine? I can see thee offets in the server code but no idea of what values are (or I am using cheat engine incorrectly?)

**Comment by nailuj29gaming** [comment]
@termitavee I'm already working on this, I just haven't had much time. I should be able to work on this later today.

**Comment by nailuj29gaming** [comment]
How do I get past the obfuscation? 
![image](https://user-images.githubusercontent.com/54189157/101818522-fcef4280-3af1-11eb-92cb-7e24069e3aa0.png)

**Comment by nailuj29gaming** [comment]
@ottomated Would it be possible for you to make some kind of guide as to how you found the offsets in the steam game? I could likely apply those instructions to the itch version.

**Comment by termitavee** [comment]
@nailuj29gaming There is a pull request to support gamepass/epic version https://github.com/ottomated/CrewLink/pull/422, I think I may have usefull information

**Comment by OhMyGuus** [comment]
Pull request #444 should fix this as well, didn't try it yet tho since I don't own the itch.io version. 
Would be nice if someone with the itch.io version can try if it works for me by either building the branch or trying my fork 
https://github.com/OhMyGuus/BetterCrewLink/releases

Be aware the open the game button isn't implemented yet just open the game using the itch.io launcher

**Comment by skeetcha** [comment]
Well, I'm still having an issue with the Itch version. @OhMyGuus's version works, but it's an earlier version of CrewLink and my friends have the Steam version of the game for which the current version of CrewLink works (as well as the default server uses the newer version of CrewLink). Is there an easier way to make CrewLink work with the Itch version of Among Us _and_ the Steam version, or do all players have to have the same version for it to work completely?

**Comment by OhMyGuus** [comment]
^ at the moment 

> Well, I'm still having an issue with the Itch version. @OhMyGuus's version works, but it's an earlier version of CrewLink and my friends have the Steam version of the game for which the current version of CrewLink works (as well as the default server uses the newer version of CrewLink). Is there an easier way to make CrewLink work with the Itch version of Among Us _and_ the Steam version, or do all players have to have the same version for it to work completely?

At the moment not, updated my fork to the latest version of crew link tho. Until this pr gets merged that is your best option
